name: kalandra blog
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
#    runs-on: ubuntu-20.04
    runs-on: macos-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: kalandramo/kalandramo.github.io
          publish_dir: ./public
          publish_branch: master
          cname: www.moweilong.com
